spring.application.name=03_community

server.port=8989

#jsp vuew 경로 설정 (ViewResolver)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#db 접속 정보
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=C##SPRING
spring.datasource.password=SPRING
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# mybatis 설정
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.kh.community.member.model.dto
# DB 컬럼(MEMBER_ID)과 자바 프로퍼티(memberId)를 자동으로 매핑해줌 (select 결과 매핑에 필요)
mybatis.configuration.map-underscore-to-camel-case=true


#파일 업로드 설정
# 업로드 파일 1개 최대 크기
spring.servlet.multipart.max-file-size=10MB
# 업로드 요청의 최대 크기
spring.servlet.multipart.max-request-size=50MB

#사용자 정의 설정
# 파일 경로
file.upload-dir=uploads
file.upload-dir.profile=uploads/profile