-- ============================================================

-- 접속 계정 : C##SPRING / SPRING

-- CREATE USER C##SPRING IDENTIFIED BY SPRING;

-- GRANT CONNECT, RESOURCE TO C##SPRING; 

-- ALTER USER C##SPRING DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- ============================================================



-- 혹시 기존에 테이블이 있다면 삭제

BEGIN

    FOR t IN (SELECT table_name FROM user_tables

              WHERE table_name IN ('TB_COMMENT','TB_BOARD_IMAGE','TB_BOARD','TB_MEMBER')) LOOP

        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';

    END LOOP;

END;

/

-- 혹시 기존에 시퀀스가 있다면 삭제

BEGIN

    FOR s IN (SELECT sequence_name FROM user_sequences

              WHERE sequence_name IN ('SEQ_BOARD','SEQ_BOARD_IMAGE','SEQ_COMMENT')) LOOP

        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;

    END LOOP;

END;

/



-- 시퀀스 생성

CREATE SEQUENCE SEQ_BOARD       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_BOARD_IMAGE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_COMMENT     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;



-- 회원 테이블 생성

CREATE TABLE TB_MEMBER (

    MEMBER_ID    VARCHAR2(50)  NOT NULL,

    MEMBER_PWD   VARCHAR2(200) NOT NULL,

    MEMBER_NAME  VARCHAR2(50)  NOT NULL,

    NICKNAME     VARCHAR2(50)  NOT NULL,

    EMAIL        VARCHAR2(100),

    PROFILE      VARCHAR2(300),

    CREATE_AT    DATE          DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_MEMBER          PRIMARY KEY (MEMBER_ID),

    CONSTRAINT UQ_MEMBER_NICKNAME UNIQUE (NICKNAME)

);

COMMENT ON TABLE  TB_MEMBER IS '회원';

COMMENT ON COLUMN TB_MEMBER.MEMBER_ID   IS '로그인 아이디(PK)';

COMMENT ON COLUMN TB_MEMBER.MEMBER_PWD  IS '암호화된 비밀번호';

COMMENT ON COLUMN TB_MEMBER.MEMBER_NAME IS '이름';

COMMENT ON COLUMN TB_MEMBER.NICKNAME    IS '닉네임';

COMMENT ON COLUMN TB_MEMBER.EMAIL       IS '이메일';

COMMENT ON COLUMN TB_MEMBER.PROFILE     IS '프로필 이미지 저장 경로';

COMMENT ON COLUMN TB_MEMBER.CREATE_AT   IS '가입일시';



-- 게시글 테이블 생성

CREATE TABLE TB_BOARD (

    BOARD_ID   NUMBER(19)    NOT NULL,

    MEMBER_ID  VARCHAR2(50),

    CATEGORY   VARCHAR2(20)  DEFAULT '자유' NOT NULL,

    TITLE      VARCHAR2(200) NOT NULL,

    CONTENT    CLOB          NOT NULL,

    COUNT      NUMBER(10)    DEFAULT 0 NOT NULL,

    CREATE_AT  DATE          DEFAULT SYSDATE NOT NULL,

    UPDATE_AT  DATE          DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_BOARD        PRIMARY KEY (BOARD_ID),

    CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY (MEMBER_ID)

               REFERENCES TB_MEMBER(MEMBER_ID) ON DELETE SET NULL

);

COMMENT ON TABLE  TB_BOARD IS '게시글';

COMMENT ON COLUMN TB_BOARD.BOARD_ID  IS '게시글 번호(PK)';

COMMENT ON COLUMN TB_BOARD.MEMBER_ID IS '작성자(FK, 회원탈퇴시 NULL)';

COMMENT ON COLUMN TB_BOARD.CATEGORY  IS '카테고리(자유/질문/공지 등)';

COMMENT ON COLUMN TB_BOARD.TITLE     IS '제목';

COMMENT ON COLUMN TB_BOARD.CONTENT   IS '내용';

COMMENT ON COLUMN TB_BOARD.COUNT     IS '조회수';

COMMENT ON COLUMN TB_BOARD.CREATE_AT IS '작성일';

COMMENT ON COLUMN TB_BOARD.UPDATE_AT IS '수정일';



-- 게시글 첨부이미지 테이블 생성

CREATE TABLE TB_BOARD_IMAGE (

    IMAGE_ID      NUMBER(19)    NOT NULL,

    BOARD_ID      NUMBER(19)    NOT NULL,

    ORIGINAL_NAME VARCHAR2(300) NOT NULL,

    SAVE_NAME     VARCHAR2(300) NOT NULL,

    IMAGE_PATH    VARCHAR2(300) NOT NULL,

    IMAGE_ORDER   NUMBER(10)    DEFAULT 0 NOT NULL,

    CREATE_AT     DATE          DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_BOARD_IMAGE  PRIMARY KEY (IMAGE_ID),

    CONSTRAINT FK_BOARD_IMAGE  FOREIGN KEY (BOARD_ID)

               REFERENCES TB_BOARD(BOARD_ID) ON DELETE CASCADE

);

COMMENT ON TABLE  TB_BOARD_IMAGE IS '게시글 이미지';

COMMENT ON COLUMN TB_BOARD_IMAGE.IMAGE_ID      IS '이미지번호(PK)';

COMMENT ON COLUMN TB_BOARD_IMAGE.BOARD_ID      IS '게시글 번호(FK)';

COMMENT ON COLUMN TB_BOARD_IMAGE.ORIGINAL_NAME IS '업로드시 원본 파일명';

COMMENT ON COLUMN TB_BOARD_IMAGE.SAVE_NAME     IS '서버에 저장된 이름(동일이름 충돌방지)';

COMMENT ON COLUMN TB_BOARD_IMAGE.IMAGE_PATH    IS '서버 저장 경로';

COMMENT ON COLUMN TB_BOARD_IMAGE.IMAGE_ORDER   IS '대표이미지 정보(0=대표이미지)';

COMMENT ON COLUMN TB_BOARD_IMAGE.CREATE_AT     IS '이미지 업로드 날짜';



-- 댓글 테이블 생성

CREATE TABLE TB_COMMENT (

    COMMENT_ID  NUMBER(19)     NOT NULL,

    BOARD_ID    NUMBER(19)     NOT NULL,

    MEMBER_ID   VARCHAR2(50),

    CONTENT     VARCHAR2(1000) NOT NULL,

    CREATE_AT   DATE           DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_COMMENT        PRIMARY KEY (COMMENT_ID),

    CONSTRAINT FK_COMMENT_BOARD  FOREIGN KEY (BOARD_ID)

               REFERENCES TB_BOARD(BOARD_ID) ON DELETE CASCADE,

    CONSTRAINT FK_COMMENT_MEMBER FOREIGN KEY (MEMBER_ID)

               REFERENCES TB_MEMBER(MEMBER_ID) ON DELETE SET NULL

);

COMMENT ON TABLE  TB_COMMENT IS '댓글';

COMMENT ON COLUMN TB_COMMENT.COMMENT_ID IS '댓글번호(PK)';

COMMENT ON COLUMN TB_COMMENT.BOARD_ID   IS '게시글 번호(FK)';

COMMENT ON COLUMN TB_COMMENT.MEMBER_ID  IS '작성자(FK, 회원탈퇴시 NULL)';

COMMENT ON COLUMN TB_COMMENT.CONTENT    IS '댓글 내용';

COMMENT ON COLUMN TB_COMMENT.CREATE_AT  IS '댓글 작성일';



-- 관리자 계정 초기 데이터

INSERT INTO TB_MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, NICKNAME, EMAIL)

VALUES ('admin', '1234', '홍길동', '길동이', 'admin@kh.co.kr');



COMMIT;